### ISSUE TITLE
Parameterize index selection

### ISSUE THREAD

**Issue by hillelt** [allenai/odinson#4]
odinson is started as a docker image which has an index baked into the image. This means that if we want to change the index we need to create another (large) docker image, upload it to the cloud, etc. This creates an unscalable mess of containers in GCR and wastes a lot of time in creating/uploading containers.

Instead, we'd like to create a docker image with only the code, and have it download its index when first started based on parameters propagated from docker-compose.yml. Once implemented, changing the an index will only require specifying the index path in docker-compose.yml -- there will be no need to create/upload new containers.

**Comment by hillelt** [comment]
Per a conversation with @mcshlain and @yoavg, for each dataset we'll create a versioned folder on cloud storage: e.g. `gs://ai2i/SPIKE/datasets/<dataset_name>/<dataset-version>` which will contain:

* the annotated dataset (what currently sits in `server/resources/dataset/<dataset_name>`).
* the odinson index.
* the SPIKE cache.
* a config file with all the required options to create and load the index

To start SPIKE, we'll use `docker-compose up` as usual, but we'll modify the startup command of the different containers (annotator, odinson and spike) to a script that:
* downloads the required data files to a container folder that's mounted to local storage
  * For speed, if the data files are already in the mounted directory they will not be re-downloaded.  
* calls the original startup command.

In this issue I'll make the required changes to the odinson docker image per the above description.

**Comment by hillelt** [comment]
I’m currently creating a `gs://ai2i/SPIKE/datasets/<dataset_name>/<dataset_version>` folder on cloud storage where the version is just a number we can manually control (I'm starting it from 1.0). The files below this folder are named by the dataset: 

* `<dataset_name>-ann.tar.gz` contains the dataset files
* `<dataset_name>-odinson-index.tar.gz` is the odinson index
* `<dataset_name>-spike-index.tar.gz` is the SPIKE cache/index
* `<dataset_name>-config.yml` is the dataset specific configuration file.

The advantage of this scheme is that it's nice and tidy. The disadvantage is that if we now update the cache file, we need to copy all artifacts into a new folder (v 2.0), which is wasteful (no symlinks in cloud storage, apparently). One alternative we can consider is to version the dataset, index and cache separately (e.g. in separte folders under `gs://ai2i/SPIKE/datasets/<dataset_name>`, or using any other ad-hoc method) and have the config file be the only versioned file in `gs://ai2i/SPIKE/datasets/<dataset_name>/<dataset_version>` and list the versions/paths of the other artifacts. This complicates things but is less wasteful.

@mcshlain @yoavg any thoughts?

**Comment by yoavg** [comment]
i am ok with the waste for now. (how many versions do we expect to have?)

is the "dataset files" what is currently stored in the "ann" folder? if so,
better to add the "-ann." to the filename (like in odinson, spike-cache...)
and also add a potential "-raw" version for what was there before the "-ann"

**Comment by mcshlain** [comment]
I think we will need individual versions for the different parts, it's very likely that we say annotate once, but generate multiple indexes as we modify the odinson indexing code. I think the configuration should have different versions for each part, so we can for example run the 1.0 version of ann but the 1.2-test-something version for the odinson index. Can versions contain words to say mark experiments?

How do we determine the `latest` version in the scheme? I don't think we ever discussed this.

I agree with yoav that it would be nice to put the `-raw` version there as well. 
Also I'd change the name of `spike-cache` to `spike-index` or `dataset-index`, it's a file based cache of an index.

**Comment by hillelt** [comment]
Yes, the dataset files are the ann dir, I'll make the change and I edited the original comment to reflect. 

As for the raw version, it actually makes more sense for me to put it in a separate hierarchy (we already have `gs://ai2i/datasets` and `gs://ai2i/LDC` for this -- we should at least unify these 2). The reason for this is that (a) the datasets are SPIKE agnostic and (b) there's isn't always a 1-1 correlation (e.g. from the raw tacred datafiles we created 3 separate SPIKE datasets (`tacred-train-labeled`, `tacred-dev-labeled` and `tacred-test-labeled`). What do you think?

As for the latest version, I was thinking that would be maintained in the commited `docker-compose.yml` file. These will include the dataset name and version of the different datasets.

Re spike-cache/spike-index, I'll make the change and I've modified the original comment to reflect.

As for @mcshlain question re words in version numbers, I don't see an issue with that (so seems possible). In general, I agree versioning the individual files makes sense, but it complicates things a bit. Let's discuss this in person tomorrow.

**Comment by mcshlain** [comment]
Ok, based on your description, I think the raw files do belong somewhere else if we don't have a 1-to-1 mapping. 

Latest version in docker compose, is a solution I'm fine with.

And yes lets discuss the versioning of individual parts tomorrow.

**Comment by yoavg** [comment]
sounds good to me.

my two cents is that I think I am OK with a solution that duplicates data,
but I wouldn't want to duplicate computation.
so if we have versions in Hillel's way, we should allow the creation
process of a new dataset to copy some parts from a previous dataset rather
than create from scratch.

**Comment by hillelt** [comment]
Adding to the discussion tomorrow, a possible middle ground: we can version all the artifacts separately in whichever scheme we choose, but we make sure the "latest" is always copied to a designated directory under `gs://ai2i/SPIKE/datasets/<dataset_name>/latest` (with a README file saying where each artifact was taken from). It's a somewhat ugly solution but it has its own tradeoff of pros and cons so it's something to consider.

**Comment by hillelt** [comment]
A way to automate the suggestion in my previous comment is to use [Bucket Object Versioning](https://cloud.google.com/storage/docs/object-versioning). It also seems to be the recommended way to [store artifacts when using Cloud Build ](https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts) (Google is also working on Google Cloud Artifacts which supports Maven and npm packges, but it doesn't look mature). 

The advantage is that you have a single folder with the recent version of all the dataset related artifacts. You also have "archived" copies of all the previous versions of the artifacts. The problem, similarly to the suggestion in my previous comment, is that if you want to roll back all artifacts together to a specific point in SPIKE's history, that's tricky.

**Comment by mcshlain** [comment]
If we want to use the bucket versioning we will need a separate bucket for these artifacts, I don't think there is a reason to activate versioning on all of ai2i. I also think that having the version just a generation number is limiting but we can probably live with it and just name the data sets differently if we do some sort of experiment where we don't want to override the dataset.

**Comment by hillelt** [comment]
Ready for review: 
PR in odinson: https://github.com/allenai/odinson/pull/7
PR in SPIKE: https://github.com/allenai/spike/pull/251

Based on a final discussion with Micah and Yoav, we'll keep all the different version of a dataset  files under gs://ai2i/SPIKE/dataset/<dataset_name> and use environment variables to communicate to the different containers from where they should download their data artifacts. 

I created gs folder for tacred-train-labeled and suppai (`gsutil ls gs://ai2i/SPIKE/datasets`) but didn't bother to do it also for bio-spike and kbp which I assume are basically legacy (and they still work with their current config based on an odinson with baked index).

To start spike or spike-suppai, as usual, just run:
```
>> docker-comopse up --build
```
OR
```
>> docker-compose -f docker-compose-suppai.yml up --build
```
The first time SPIKE starts it will download an odinson index to `SPIKE_ROOT/data/odinson-index` (this local path is mounted via docker-compose). The next time it starts it will used the cached index. Modifying the environment variable INDEX_URL before running `docker-compose up` will cause SPIKE to fetch the index from a different path (assuming no cache). This is probably fine for search but if used in SPIKE you'll have to make sure the new index corresponds to the dataset baked into the SPIKE image.

**Comment by hillelt** [comment]
Also note: when the odinson container starts it should print whether it reads the index from local cache or from cloud storage (if from cloud storage, the exact path should be printed).

**Comment by mcshlain** [comment]
Merged the relevant PRs here and in spike.
