### ISSUE TITLE
Add ability for a filtering query in the API

### ISSUE THREAD

**Issue by mcshlain** [allenai/odinson#5]
The basic idea is to add another query to the API, similar to the parentQuery that will also allow to filter the results based on some additional metadata available on the lucene documents. 

Because some of the metadata we might want is not available in the Index, we also want a simple way to expand the indexing process by adding more metadata to sentences.

The basic design is to provide hooks in odinson in two places:
1. At indexing time, to allow the addition of more metadata to the index
2. At search time to supplement the searchQuery with additional constraints (based on metadata in the index) - this will ustilize the new query added to the API as input.

In addition we can group the two corresponding hooks as a single plugin and we should be able to  define a list (or hierarchy) of plugins to load using configuration.
  
Open questions:
1. When using multiple plugins how exactly will they interact? Are they aware of each other or are they not? How do we split the query from the API to send only the relevant parts of the query to every plugin. 
2. What should happen if the index does not contain the metadata expected by a plugin? For example if there was a mismatch where the index was created without the plugin but is trying to run a query with it. Can we somehow store this metadata (what plugins were used in creating the index) in the index itself so that this can be validated when odinson back end is getting up?

**Comment by yoavg** [comment]
I am not sure I fully understand the "plugin" aspect of this.
What will the plugin do?

What I had in mind is to have this specified in an extended version of the "ann" jsons, basically supplementing the format with a new field that specifies a dictionary with additional data to load and the field names in which each piece of data is loaded, and maybe their types.[*] 

What will the plugin provide on top of this capability?

[*] maybe the type information etc can be done in some additional, ann-external config file.

**Comment by mcshlain** [comment]
A plugin is just the definition of two corresponding hooks, one that will add metadata to the index during indexing and the second hook will enrich the lucene query based on the new search term. 

One implementation could be what you are suggesting, the indexing hook will read the extra information from the ann and add it. And a general lucene query addition the query this information. 

I think that what you are suggesting is a limited version of this, also I wouldn't want to add information that is made specifically for indexing at the generation of anns stage. 
With code that interacts with the document and the search query we will have more flexibility to do things that are no necessary just a dictionary of things.

**Comment by yoavg** [comment]
got it.
as long as we also have the option to specify whichever extra fields we
want without touching the indexer code (for example by adding to the ann
jsons), i am happy.

**Comment by mcshlain** [comment]
No longer relevant
