### ISSUE TITLE
Add ability to filter results based on word in sentence

### ISSUE THREAD

**Issue by mcshlain** [allenai/odinson#6]
Based on the API described in #5 

<strike>We want a simple query filter that can in addition to the odinson pattern, retrieve only sentences that contain some specific word in the sentence (doesn't have to be connected at all to the pattern expressed). </strike>

Add the ability to specify any lucene query in addition to the odinson query to filter results.

**Comment by yoavg** [comment]
Why restrict to a single word though? 

If we allow *any* lucene query on the indexed data, we can get rich results "for free". 

If the user enters a word or several words, it will do word search, but they can also do word-proximity search, or search over specific fields. We just need to make sure that the default search (if no field is specified in the query) goes to the words field.

**Comment by mcshlain** [comment]
@yoavg 
I changed the description according to your comment.

**Comment by mcshlain** [comment]
was already implemented with sentence queries.
